### ISSUE TITLE
Using optional configuration fails with `unknown directive "cache_purge_response_type"`

### ISSUE THREAD

**Issue by witrin** [nginx-modules/ngx_cache_purge#18]
Whenever I try to use the optional configuration directive `cache_purge_response_type` NGINX fails with:

`unknown directive "cache_purge_response_type" in [...]`

Here is what I got:

 * Build configuration: `--conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-http_ssl_module --with-http_v2_module --add-dynamic-module=../ngx_http_geoip2_module-2.0 --add-dynamic-module=../ngx_http_cache_purge_module-2.4.2`
 * NGINX version: `1.12.2`
 * OS: `Ubuntu 16.04.5 `

I've tried every context without success. Beside that it works! :)

**Comment by denji** [comment]
> --add-dynamic-module=../ngx_http_cache_purge_module-2.4.2

```nginx
#user  ....;
#worker_processes  ...

load_module modules/ngx_http_cache_purge_module.so;

#error_log...
#...
http {
   # ....
}
```

cache_purge_response_type
-----------------
* __**context**: `http`, `server`, `location`__

**Comment by denji** [comment]
**cache_purge_response_type** work only [git-master](https://github.com/nginx-modules/ngx_cache_purge/archive/master.tar.gz) version.

- 2.4.2 not support cache_purge_response_type

**Comment by witrin** [comment]
Ah my bad! I'm sorry for this! Thank you very much!

**Comment by denji** [comment]
https://github.com/nginx-modules/ngx_cache_purge/releases/tag/2.5
