### ISSUE TITLE
Crash on purge request starting from nginx 1.11.6

### ISSUE THREAD

**Issue by p-golovin** [nginx-modules/ngx_cache_purge#2]
[gdb-bt-full.txt](https://github.com/nginx-modules/ngx_cache_purge/files/791118/gdb-bt-full.txt)
[nginx-version.txt](https://github.com/nginx-modules/ngx_cache_purge/files/791117/nginx-version.txt)

**Comment by p-golovin** [comment]
This fork (https://github.com/DreamLab/ngx_cache_purge/commit/c7345057ad5429617fc0823e92e3fa8043840cef) seems to be fine, but I`m not sure that this fix all that needed

**Comment by denji** [comment]
https://github.com/nginx-modules/ngx_cache_purge/releases
