### ISSUE TITLE
How to purge any Accept-Encoding cache ?

### ISSUE THREAD

**Issue by foxbin** [nginx-modules/ngx_cache_purge#20]
find  /data/proxy_cache/ -type f  |wc -l
0

192.168.60.99 m.xx.com - - [10/Aug/2018:01:35:47 +0800] "GET /purge/ask/118060.html HTTP/1.1" 412 186 - "-" "python-requests/2.19.1" "-" "-""0.000" "-" ""
192.168.60.99 m.xx.com - - [10/Aug/2018:01:35:47 +0800] "GET /purge/ask/118060.html HTTP/1.1" 412 186 - "-" "python-requests/2.19.1" "-" "-""0.000" "-" "gzip"
192.168.60.99 m.xx.com - - [10/Aug/2018:01:35:47 +0800] "GET /ask/118060.html HTTP/1.1" 200 23294 - "-" "python-requests/2.19.1" "-" "-""0.001" "MISS" ""
192.168.60.99 m.xx.com - - [10/Aug/2018:01:35:47 +0800] "GET /ask/118060.html HTTP/1.1" 200 5863 - "-" "python-requests/2.19.1" "-" "-""0.001" "MISS" "gzip"

find  /data/proxy_cache/ -type f  |wc -l
2

192.168.60.99 m.xx.com - - [10/Aug/2018:01:36:55 +0800] "GET /purge/ask/118060.html HTTP/1.1" 200 241 - "-" "python-requests/2.19.1" "-" "-""0.000" "-" ""
192.168.60.99 m.xx.com - - [10/Aug/2018:01:36:55 +0800] "GET /purge/ask/118060.html HTTP/1.1" 412 186 - "-" "python-requests/2.19.1" "-" "-""0.000" "-" "gzip"

find  /data/proxy_cache/ -type f  |wc -l
1

Unable to clear cache Accept-Encoding: gzip
/proxy_cache/ad/47/720ed608237b61e85ceac7d253e447ad

**Comment by denji** [comment]
Do you have the [`gzip_vary`](https://nginx.org/r/gzip_vary) option enabled?

**Comment by foxbin** [comment]
After repeated testing, it is indeed caused by this problem.
Already solved, thanks!

**Comment by denji** [comment]
https://github.com/torden/ngx_cache_purge/commit/5a45053cae6f07822459359533fb7c41b77b313e
