### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by fatihag** [nginx-modules/ngx_cache_purge#23]
I see a transaction successful message when I visit www.xxx.com/purge/*

The files in /var/cache/nginx/domain.com_proxy/ remain unchanged and the site comes from the cache again.

**Comment by denji** [comment]
https://github.com/nginx-modules/ngx_cache_purge#partial-keys

**Comment by pasamsin** [comment]
If I visit as below;
https://www.domain.com/purge/index.html*
It gives this message;
Successful purge
Key : /index.html*

If I visit as below;
https://www.domain.com/purge/index.html or https://www.domain.com/purge/
It gives this message; Why am I getting an error?
412 Precondition Failed
nginx

My configuration is as follows;
location ~ /purge(/.*) {
   allow              xxx.xxx.xxx.xxx/24;
   deny               all;
   proxy_cache_purge  domain.com_proxy $1$is_args$args;
}

**Comment by denji** [comment]
https://github.com/nginx-modules/ngx_cache_purge/releases/tag/2.5
