### ISSUE TITLE
nginx/1.19.0 response text extra null bytes

### ISSUE THREAD

**Issue by tugrul** [nginx-modules/ngx_cache_purge#25]
It always appends extra null bytes (74 bytes) to response.

**Comment by denji** [comment]
nginx-modules/ngx_cache_purge#26

**Comment by tugrul** [comment]
This problem also occurs in 1.18.0

**Comment by torden** [comment]
@tugrul, you use directive below?
{code}
    cache_purge_response_type text;
{code}

I will check up as soon~

**Comment by tugrul** [comment]
The directive doesn't affect when I put in `location` and `server` context. It works in `http` context but result doesn't changed for `text` response. It still appends null bytes (66 bytes) to text response.

I'm going to try to debug in docker container to identify problem. Probably there is something different or wrong in memory allocation code https://github.com/nginx-modules/ngx_cache_purge/blob/master/ngx_cache_purge_module.c#L1530-L1536

**Comment by tugrul** [comment]
I discovered the problem. Template doesn't have cache file path but it's length using in memory allocation.

![debug](https://user-images.githubusercontent.com/163442/85892283-504a2e80-b7f9-11ea-8f7b-da6e6b156dfc.png)

**Comment by denji** [comment]
https://github.com/nginx-modules/ngx_cache_purge/releases
