### ISSUE TITLE
412 Precondition Failed please help me

### ISSUE THREAD

**Issue by sezerkaratas** [nginx-modules/ngx_cache_purge#38]
my config is like this

    fastcgi_cache_path /etc/nginx-cache levels=1:2 keys_zone=WORDPRESS:1400m inactive=1300m;
    fastcgi_cache_key "$request_uri$mobile_request";

fastcgi_cache_purge PURGE from 127.0.0.1;

location ~ /purga(/.*)?.* {
 fastcgi_cache_purge WORDPRESS "$1mobileversion";
 
}
curl -X GET  example.com/purga/example

its work but

curl -X PURGE  example.com/example

412 Precondition Failed

I've been trying to solve it for over a week, please help. No matter what I do I can't solve the problem. please help please

**Comment by yuriylygin** [comment]
Try doing this:

    curl -X PURGE example.com/purga/example

not 

    curl -X PURGE example.com/example

If `curl -X GET example.com/purga/example` worked, `curl -X PURGE example.com/purga/example` may well work too.

**Comment by ChekhWasTaken** [comment]
hi! i am having the same issue:
here are my configs:
```
load_module modules/ngx_http_cache_purge_module.so;

http {
    gzip off;
    gzip_vary off;
    gzip_proxied off;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    proxy_cache_path /var/cache/nginx/proxy_cache levels=1:2 use_temp_path=off keys_zone=proxycache:256m
    inactive=30d
    max_size=4g;

    proxy_cache_purge PURGE from 127.0.0.1;

    server {
        listen *:8008;
        location ~* /purgea(/.*) {
            add_header X-url-match $scheme${request_method}my_proxy_server$1$args always;
            proxy_cache_purge proxycache $scheme${request_method}my_proxy_server$1$args;
            cache_purge_response_type json;
        }
    }
}
```
I am using a docker image with nginx and ngx_cache_purge. here is how i build it.
```Dockerfile
FROM nginx:1.18.0

RUN apt update && apt install -y --no-install-recommends  --no-install-suggests \
            wget gcc make zlib1g-dev libpcre3-dev

RUN mkdir -p /home/nginx && cd /home/nginx && \
    wget -qO - https://nginx.org/download/nginx-1.18.0.tar.gz | tar zxfv - && \
    wget -qO - https://github.com/nginx-modules/ngx_cache_purge/archive/refs/tags/2.5.1.tar.gz | tar zxfv -

RUN cd /home/nginx/nginx-1.18.0 && \
    ./configure --add-dynamic-module=../ngx_cache_purge-2.5.1 --with-compat && \
    make modules && \
    cp objs/ngx_http_cache_purge_module.so /usr/lib/nginx/modules/ 
```

**Comment by denji** [comment]
[`proxy_cache_purge on|off|<method> [purge_all] [from all|<ip> [.. <ip>]]`](https://github.com/nginx-modules/ngx_cache_purge#proxy_cache_purge)

`on|off` - disable/enable all supported HTTP method's
`[purge_all] [from all|<ip> [.. <ip>]]` optional

**Comment by denji** [comment]
proxy_cache_key proxycache $scheme${request_method}my_proxy_server$1$args;
fastcgi_cache_key WORDPRESS "$1mobileversion";

**Comment by denji** [comment]
@ChekhWasTaken
```nginx
proxy_cache proxycache;
proxy_cache_key "$scheme${request_method}my_proxy_server$1$args";
```

@sezerkaratas
```nginx
fastcgi_cache_path /etc/nginx-cache levels=1:2 keys_zone=WORDPRESS:1400m inactive=1300m;
fastcgi_cache_key "$request_uri$mobile_request";
server {
  fastcgi_cache_purge PURGE from 127.0.0.1;
  location ~ /purga(/.)? {
    fastcgi_cache WORDPRESS
    fastcgi_cache_key "$1mobileversion";
   }
}
```
