### ISSUE TITLE
nginx: [emerg] invalid parameter "purge_all"

### ISSUE THREAD

**Issue by szabyka** [nginx-modules/ngx_cache_purge#39]
When I try to save: 

location ~ /purgeall {
        fastcgi_pass         localhost:8001;
        fastcgi_cache        xyz.com;
	fastcgi_cache_key    $uri$is_args$args;
        fastcgi_cache_purge PURGE purge_all from 127.0.0.1;
	}

Failed to save configuration file : Configuration is invalid : nginx: [emerg] invalid parameter "purge_all", expected "from" keyword in /etc/nginx/sites-enabled/xyz.com.conf:49 nginx: configuration file /etc/nginx/nginx.conf test failed

nginx version: nginx/1.14.1

Has anyone had the same issue?

**Comment by szabyka** [comment]
> https://github.com/nginx-modules/ngx_cache_purge/blob/2.5.1/ngx_cache_purge_module.c#L1874

Thanks @denji , but not sure I understand what you mean?

**Comment by denji** [comment]
@szabyka Can you test on nginx [stable and mainline versions](https://nginx.org/en/download.html)?

**Comment by szabyka** [comment]
@denji 
I am not able to test it with different nginx versions atm.

Yes, I used your fork, below the `nginx - V` output.

`nginx version: nginx/1.14.1
built by gcc 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC) 
built with OpenSSL 1.1.1 FIPS  11 Sep 2018 (running with OpenSSL 1.1.1k  FIPS 25 Mar 2021)
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-http_auth_request_module --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'`

**Comment by denji** [comment]
@szabyka 

```
# cat /etc/redhat-release
AlmaLinux release 8.5 (Arctic Sphynx)
# nginx -V
nginx version: nginx/1.14.1
built by gcc 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC) 
built with OpenSSL 1.1.1g FIPS  21 Apr 2020 (running with OpenSSL 1.1.1k  FIPS 25 Mar 2021)
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-http_auth_request_module --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'

# mkdir -p /root/ngx_build
# cd /root/ngx_build
# wget -qOnginx-1.14.1.tar.gz https://nginx.org/download/nginx-1.14.1.tar.gz ; tar xf nginx-1.14.1.tar.gz
# wget -qOngx_cache_purge-2.5.1.tar.gz https://github.com/nginx-modules/ngx_cache_purge/archive/refs/tags/2.5.1.tar.gz ; tar xf ngx_cache_purge-2.5.1.tar.gz
# cd nginx-1.14.1
# CFLAGS=-Wno-error ./configure --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-http_auth_request_module --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E' --add-dynamic-module=../ngx_cache_purge-2.5.1
# make modules -j2

# cp -va objs/ngx_http_cache_purge_module.so /usr/lib64/nginx/modules/
# ls -l objs/ngx_http_cache_purge_module.so
-rwxr-xr-x 1 root root 155880 Feb  7 21:42 objs/ngx_http_cache_purge_module.so

# sed -i '1s@^@load_module /usr/lib64/nginx/modules/ngx_http_cache_purge_module.so;\n@'  /etc/nginx/nginx.conf
# head -1 /etc/nginx/nginx.conf
load_module /usr/lib64/nginx/modules/ngx_http_cache_purge_module.so;

# nginx -s reload

# cat /etc/nginx/conf.d/demo.conf
fastcgi_cache_path  /tmp/fcgi_xyz.com  keys_zone=xyz.com:1m;
server {
 listen 80;
 #listen [::]:80;
 server_name test.localhost;
 location ~ /purgeall {
  fastcgi_pass localhost:8001;
  fastcgi_cache xyz.com;
  fastcgi_cache_key $uri$is_args$args;
  fastcgi_cache_purge PURGE purge_all from 127.0.0.1;
 }
}

# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by szabyka** [comment]
Update: I've started again and compiled the module based on your instructions @denji and success I can save the conf file with no issues, but the `/purgeall` still gives me the File not found page. Weird as the `/purge/*` works now.
![image](https://user-images.githubusercontent.com/6563669/152990718-856cb234-319c-499f-9457-696d2458c8a8.png)

**Comment by denji** [comment]
@szabyka HTTP Method = PURGE

**Comment by szabyka** [comment]
> 

@denji 

Yes, it's a PURGE nothing else.

```
location ~ /purgeall {
        fastcgi_pass php-fpm;
        fastcgi_cache        szabi.ml;
        fastcgi_cache_purge PURGE purge_all from 127.0.0.1;
	}
```

`curl -X PURGE https://szabi.ml/purgeall`

`<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>`

What am I missing?

**Comment by denji** [comment]
Wrong vhost section is selected or the client's ip does not match the whitelist.
